// One-off seeded generator. Run with `node lib/generate-deals.ts` and paste
// the printed array literal into data/deals.ts. Not imported at runtime —
// see PLAN.md's "data sources" decision for why.
import { AS_OF_DATE, STAGES } from "./types.ts";
import type { Deal, Stage } from "./types.ts";

function mulberry32(seed: number) {
  let state = seed;
  return function random() {
    state |= 0;
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rand = mulberry32(31); // seed = day number in the 100-day series

function pick<T>(pool: T[]): T {
  return pool[Math.floor(rand() * pool.length)];
}

function daysFromAsOf(days: number): string {
  const d = new Date(`${AS_OF_DATE}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

const ACCOUNTS = [
  "Northbridge Analytics", "Cascade Freight", "Elmtree Health", "Vantage Retail",
  "Ridgeline Insurance", "Fernway Media", "Copperfield Logistics", "Brightwell Finance",
  "Thistledown Foods", "Marlow Manufacturing", "Sablewood Systems", "Ashgrove Higher Ed",
  "Halcyon Robotics", "Pemberton Supply", "Stonecrest Capital", "Windrow Energy",
  "Larkspur Insurance", "Overton Media", "Greyfriar Logistics", "Hollowell Retail",
  "Kestrel Analytics", "Dunmore Manufacturing", "Wrenfield Health", "Amberlyn Finance",
  "Birchgate Systems", "Copperleaf Foods", "Ironhold Freight", "Millhaven Robotics",
  "Sagebrook Capital", "Tallowmere Energy",
];

const OWNERS = [
  "Priya Shah", "Marcus Lee", "Dana Ferreira", "Tom Bakshi", "Elena Cruz",
  "Sam Okafor", "Jules Renner", "Nadia Voss", "Chris Palko", "Anya Torres",
];

// Per-stage config: [count, amount range, probability range, close-date
// window in days from AS_OF_DATE]. Close-date windows skew toward the last
// ~6 weeks of the quarter so the slippage lever has visible deals to push
// past the quarter boundary; a smaller tail already sits in next quarter.
const STAGE_CONFIG: Record<Stage, {
  count: number;
  amount: [number, number];
  probability: [number, number];
  closeDaysInQuarter: [number, number];
  closeDaysNextQuarter: [number, number];
  inQuarterShare: number;
}> = {
  Prospecting: {
    count: 70,
    amount: [5000, 60000],
    probability: [0.05, 0.2],
    closeDaysInQuarter: [10, 30],
    closeDaysNextQuarter: [31, 90],
    inQuarterShare: 0.5,
  },
  Qualification: {
    count: 60,
    amount: [8000, 90000],
    probability: [0.15, 0.35],
    closeDaysInQuarter: [5, 25],
    closeDaysNextQuarter: [26, 80],
    inQuarterShare: 0.6,
  },
  Proposal: {
    count: 45,
    amount: [15000, 150000],
    probability: [0.35, 0.6],
    closeDaysInQuarter: [-5, 20],
    closeDaysNextQuarter: [21, 60],
    inQuarterShare: 0.75,
  },
  Negotiation: {
    count: 25,
    amount: [20000, 250000],
    probability: [0.55, 0.9],
    closeDaysInQuarter: [-10, 15],
    closeDaysNextQuarter: [16, 45],
    inQuarterShare: 0.85,
  },
};

function randIn([min, max]: [number, number]): number {
  return min + rand() * (max - min);
}

const usedAccounts = new Set<string>();
function nextAccount(): string {
  const available = ACCOUNTS.filter((a) => !usedAccounts.has(a));
  const pool = available.length > 0 ? available : ACCOUNTS;
  const chosen = pick(pool);
  usedAccounts.add(chosen);
  return chosen;
}

const deals: Deal[] = [];
let counter = 1;

for (const stage of STAGES) {
  const config = STAGE_CONFIG[stage];
  for (let i = 0; i < config.count; i++) {
    const inQuarter = rand() < config.inQuarterShare;
    const closeDays = Math.round(
      inQuarter ? randIn(config.closeDaysInQuarter) : randIn(config.closeDaysNextQuarter),
    );
    const stageEnteredDays = -Math.round(5 + rand() * 55);

    deals.push({
      id: `deal-${String(counter).padStart(3, "0")}`,
      account: nextAccount(),
      owner: pick(OWNERS),
      amount: Math.round(randIn(config.amount) / 500) * 500,
      stage,
      stageEnteredDate: daysFromAsOf(stageEnteredDays),
      expectedCloseDate: daysFromAsOf(closeDays),
      repProbability: Math.round(randIn(config.probability) * 100) / 100,
    });
    counter++;
  }
}

if (deals.length !== 200) {
  throw new Error(`Expected 200 deals, built ${deals.length}`);
}

const body = deals
  .map((d) => {
    return `  {
    id: "${d.id}",
    account: "${d.account}",
    owner: "${d.owner}",
    amount: ${d.amount},
    stage: "${d.stage}",
    stageEnteredDate: "${d.stageEnteredDate}",
    expectedCloseDate: "${d.expectedCloseDate}",
    repProbability: ${d.repProbability},
  }`;
  })
  .join(",\n");

console.log(`import type { Deal } from "@/lib/types";

// Generated by lib/generate-deals.ts (seed 31). Do not hand-edit — rerun
// the generator and re-paste if the pipeline needs to change.
export const deals: Deal[] = [
${body},
];
`);
